### ISSUE TITLE
Creëer nieuwsbericht voor bouncecamp hans vanwijn

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#27]
![image 1](https://user-images.githubusercontent.com/471354/45416331-00c85c00-b680-11e8-9db5-057df6897c08.png)

### Actieplan
 - [ ] Schrijf tekst
- [ ] Zoek image
- [ ] Maak Pull Request

**Comment by DPEWillems** [comment]
De website https://www.hansvanwijn.be/kampen/ geeft voldoende (praktische) informatie. Een korte motivatie om er aan mee te doen zou er nog bij mogen: wat maakt dit kamp de moeite waard, wat is de meerwaarde?

**Comment by yvesgoeleven** [comment]
@DPEWillems Hans is een ex speler van lummen, daarom willen we het promoten. Dit is ook een feit dat we zeker willen vermelden. Verder is de coaching staff samengesteld uit ex coaches van LimUtd, dus ze hebben bergen ervaring

**Comment by DPEWillems** [comment]
Zeker goede argumenten, maar misschien is het ook van belang om te melden wat de jeugdspelers er van kunnen bijleren (van uit hun standpunt bekeken). Zo een motivatietekst kan kort maar krachtig zijn...

**Comment by yvesgoeleven** [comment]
> om te melden wat de jeugdspelers er van kunnen bijleren

Sounds good!

**Comment by PeterWouters** [comment]
Geen idee wat ze gaan bijleren. Vlgs mij is het puur commercieel gericht. Er worden tegenwoordig langs alle kanten kampen uit de grond gestampt waarbij we zelfs niet eens weten wie de coaches zijn. Zij noemen maar 3 coaches en ik ken Ronny McCollum en Christophe Albergs. degelijke coaches, maar op landelijk en nationaal niveau!
Ik heb persoonlijk veel meer vertrouwen in het FROS kamp day ook door Bart Wouters georganiseerd wordt tijdens de eerste week van de kerstvakanti. FROS is al jaren een vaste speler in Limburg en stoelt op hopen ervaring. Zij leveren altijd locale coaches (Jolien Wouters, Janne Wouters, Caro Swolfs) en hebben een ijzersterk concept voor beginnende en ietwat gevorderde basketters. FROS heeft GEEN oplossing voor de landelijke spelers! FROS organiseert een kamp in Lummen tijdens de eerste week van de kerstvakantie. Dus als je reclame maakt voor Vanwijn, dan ook graag voor FROS.
Let wel ... ik heb geen aandelen in FROS. Ik weet alleen dat mijn kinderen daar jarenlang heel graag naartoe gegaan zijn, maar dat ze nu (Luka is U16) gewoon te oud zijn. FROS is een prima oplossing voor U14 (en jonger).

**Comment by yvesgoeleven** [comment]
@PeterWouters FROS staat uiteraard ook op het programma, https://github.com/BasketLummen/Communicatie/issues/48

Ik denk dat we moeten wachten op de feedback om te weten op welk niveau bouncecamp gaat zitten, vorig jaar is Ronny McCollum ook eens komen training geven bij ons en toen was dat heel basic shooting techniques. Zou dus wel kunnen dat ze zich op dat niveau houden en ook niets voor hoog niveau doen. Ze gaan ook maar tot U16.

Maar idd, na U16 is er niks meer, dan gaat men ook al vaak vakantie werk doen ed, dus misschien is die vraag er dan ook minder.

**Comment by DPEWillems** [comment]
Ik heb een tekst via pull request voorbereid, met de bedoeling deze verder aan te passen (review). Ik heb vooral op de teskt zelf gefocust, nog niet op de layout (foto etc.).
Misschien blijkt uit deze tekst al voldoende waarom we deze kampen steunen? Anders moeten we de uitleg er nog aan toevoegen. Van Brechts kamp krijgen we de gegevens hopelijk snel door.
