### ISSUE TITLE
Mosselfeest 2019

### ISSUE THREAD

**Issue by StefanCoenen** [BasketLummen/Communicatie#40]
affiches maken

**Comment by DPEWillems** [comment]
ter info: de tekst van 2018

Naar jaarlijkse gewoonte organiseert Basket Lummen een mosselfeest op zondag 18 februari.

Voor de beste mosselen kan je dan terecht in de gildezaal van Laren, in de Hoogstraat, van 11 u. tot 14 u. en van 17 u. tot 20 u.

Mocht je toch niet zo gek zijn van mosseltjes, dan hebben we ook nog tal van andere gerechten in de aanbieding:

Mosselen
Halve haan
Vidé
Stoofvlees
Vegetarisch
2 hamburgers
Bij al deze maaltijden zijn frieten inbegrepen.

Je kan je bestelling doorgeven via het papieren formulier dat je van je coach gaat krijgen of door onderstaande digitale formulier in te vullen, het bedrag is te betalen aan de kassa op de eetdag.

**Comment by DPEWillems** [comment]
Feiten:

datum:  2018-02-17 van 11 tot 14 en 17 tot 20h?   te controleren
plaats: Gildezaal Laren?   te controleren
aanbod: mosselen
alternatief aanbod: zelfde als 2018?   te controleren
frieten inbegrepen: zoals in 2018? te controleren
bestellen via papieren formulier?  te contolreren
bestellen via digitaal formulier? Yves werkt hier al aan
