### ISSUE TITLE
informatie gericht sturen naar de  (ouders van) 10-16-jarigen

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#45]
na publicatie op de website een link via e-mail naar (de ouders van) de doelgroep sturen...

**Comment by DPEWillems** [comment]
@yvesgoeleven ik wil graag deze issue ruim op tijd inplannen, omdat ouders vaak op tijd moeten weten of hun kind in de kerstvakantie al dan niet kan meedoen. Het label 2 months prior (dus 2 november 2018) zie ik echter niet verschijnen in het overzicht (projects)...

**Comment by yvesgoeleven** [comment]
>  Het label 2 months prior (dus 2 november 2018) zie ik echter niet verschijnen in het overzicht (projects)...

ik zal het bijmaken

**Comment by yvesgoeleven** [comment]
@DPEWillems je kan het issue assigned aan het project hier in de rechter kolom, onder de projects tab. Dan verschijnt het automatisch in de todo. heb het versleept naar 'deze maand'

**Comment by DPEWillems** [comment]
ok, is gelukt

**Comment by DPEWillems** [comment]
Het bericht staat nu op de website: http://www.basketlummen.be/news/2018-10-19-kerstkampen/

Ik stel voor het ook naar de ouders van deze kinderen te sturen (Mailchimp - rekening houdend met de AVG-privacyverklaring). Wat vinden jullie?

**Comment by yvesgoeleven** [comment]
Ik zou het naar de ploegbegeleiders sturen en hun vragen het in de respectievelijke chats te zetten

**Comment by yvesgoeleven** [comment]
Ik zou het niet naar de coaches sturen, maar naar de ploegbegeleiders

J16A	Fritz Hulsmans
J16B	        Nancy Vanmechelen
M16A	Peter Wouters
M14A	Bart Heirman
M14B	Steve Hamels
G12A	Peter Moonen
G12B	Gilbert Roggen
G12C	Roel Vanheel
G10A	Annelies Wouters
G10B	Yves Goeleven
G8A         Stefan Coenen (ad interim)

**Comment by DPEWillems** [comment]
Ok. Ik heb wel niet al deze e-mailadressen, heeft Brecht die misschien?

http://www.basketlummen.be/news/2018-10-19-kerstkampen/

**Comment by DPEWillems** [comment]
ontbrekende e-mail-adressen:
J16A	Fritz Hulsmans
J16B	Nancy Vanmechelen
M14A	Bart Heirman
M14B	Steve Hamels
G12A	Peter Moonen
G10A	Annelies Wouters

**Comment by yvesgoeleven** [comment]
@DPEWillems ik zal ze u straks mailen

**Comment by DPEWillems** [comment]
Ik stuur het rond via Mailchimp (from: jeugdcel@basketlummen.be)
