### ISSUE TITLE
Creëer nieuws bericht fros kamp

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#48]
[fros.pdf](https://github.com/BasketLummen/Communicatie/files/2489323/fros.pdf)

Hierbij toegevoegd de nieuwe folder van onze Fros Kerststage 2018 op 26-27-28 dec. ( wo-do-vrij )
Ook nu weer op drie locaties zijnde : 
Kuringen             72           Headcoach Frank Schevenels
**Lummen             72           Headcoach Bart Wouters**
Zonhoven           92           Headcoach Jos Cielen + Frank Baekelmans

Met tal van ervaren en gediplomeerde coaches zullen wij de fundamentels van basketbal trainen en verbeteren ! **Zeker onze coaches highlighten: Caro Swolfs & Jolien Wouters**

Jullie kunnen vanaf nu inschrijven via de folder of mail naar jozef.cielen@pandora.be
Vul duidelijk naam , adres , geb datum, gsm nummer etc in en duid de gewenste locatie aan  aub !!!

De plaatsen zijn beperkt tot het opgegeven aantal om de kwaliteit van ons kamp te vrijwaren.
Daarom is het best om niet te lang te wachten als u erbij wil zijn op deze leerrijke basketbalstage .

### Actieplan
 - [ ] Schrijf tekst
- [ ] Zoek image
- [ ] Maak Pull Request

**Comment by DPEWillems** [comment]
Een overkoepelende tekst schrijven die een overzicht geeft van de kampen tijdens de kerstvakantie, zodat alles overzichtelijk wordt voor de ouders om dit in te plannen (Fross, Hans Vanwijn, Brechts kamp - informatie volgt nog).

**Comment by DPEWillems** [comment]
Inhoud van de tekst:
1- inleiding
2-motivatie
3-praktische informatie 
4- inschrijving

**Comment by DPEWillems** [comment]
Ik heb een tekst via pull request voorbereid, met de bedoeling deze verder aan te passen (review). Ik heb vooral op de teskt zelf gefocust, nog niet op de layout (foto etc.). 
Misschien blijkt uit deze tekst al voldoende waarom we deze kampen steunen? Anders moeten we de uitleg er nog aan toevoegen. Van Brechts kamp krijgen we de gegevens hopelijk snel door.

**Comment by yvesgoeleven** [comment]
> Van Brechts kamp krijgen we de gegevens hopelijk snel door.

Dit zal een volgende bericht worden, we moeten er niet op wachten, gewoon zeggen dat meer info later komt.
