### ISSUE TITLE
evenement definiëren

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#50]
Gaat dit over deze wedstrijd?

 27-10-2018 | 20.30 | Basket Lummen DSE A | Royal Castors Braine DSE A | Sportcomplex Vijfsprong

Is er voor of na de wedstrijd een bijzondere activiteit?

**Comment by yvesgoeleven** [comment]
@DPEWillems ja die match willen we volgende week promoten.

Voor de sponsors is er een dinner voorzien, maar dat moet uiteraard niet publiek gecommuniceerd worden, we willen vooral de tribunes vullen

**Comment by DPEWillems** [comment]
Hoe wordt de promotie gedaan? Een bericht op de website? De sportieve prestaties zouden dan moeten aangehaald worden. Wie kan deze informatie verschaffen, om er dan een tekst van te maken?

**Comment by yvesgoeleven** [comment]
@DPEWillems overleg eens met @StefanCoenen hij heeft me hierover aangesproken nog gisteren op de eetdag, hij is al van plan het FB evenement aan te maken. Betr. tekst zal hij ook nog input hebben denk ik.

**Comment by yvesgoeleven** [comment]
Het staat online en de wedstrijd wordt ook weergegeven in de newsgrid, dat zou normaal gezien voldoende moeten zijn.

**Comment by yvesgoeleven** [comment]
Het staat online en de wedstrijd wordt ook weergegeven in de newsgrid, dat zou normaal gezien voldoende moeten zijn.
