### ISSUE TITLE
Foto´s voor sponsorwedstrijd

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#52]
Is het nodig foto´s te maken?
Indien ja, waar moet de nadruk op liggen?
- publiek?
- sponsor zichtbaarheid reclame?
- sportieve prestaties/acties?
- sponsors (personen/activiteit)?
Wie kan/wil dit?

**Comment by yvesgoeleven** [comment]
In volgorde van belangrijkheid zou ik zeggen:

- sportieve acties (prestaties niet)
- sponsors activiteit (personen niet)
- publiek (enkel indien tribune vol)
- sponsors reclame

**Comment by DPEWillems** [comment]
Ook hier kan ik niet met zekerheid zeggen of ik aanwezig zal kunnen zijn (wedstrijd Tongeren 16h00 tot ...?)

**Comment by DPEWillems** [comment]
15-12-2018 | 20.30 | Basket Lummen DSE A | Kangoeroes Pitzemburg Mechelen DSE A | Sportcomplex Vijfsprong

**Comment by yvesgoeleven** [comment]
Foto's staan online
