### ISSUE TITLE
Sinterklaas 2018 - tekst schrijven 

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#54]
aanmelden van het evenement via:
- website?
- mailing?
- coaches?
-ploegbegeleiders?

**Comment by DPEWillems** [comment]
welke datum?

**Comment by DPEWillems** [comment]
Marlies: woensdag 5 december voorgesteld - overlegt nog met de andere coaches. Voor U12 is er geen Sintbezoek maar wel een zak snoep...

**Comment by DPEWillems** [comment]
tekst in Pull request aangemaakt (branch 2018-12-05 Sinterklaas-1)

**Comment by DPEWillems** [comment]
Marlies:
Wij verwittigen de u6 dat ze een keer op woensdag trainen. De rest is sowieso aanwezig!

Ik zou er geen uur bijzetten. De sint komt gewoon tijdens die training. Voor de rest prima! 😉

**Comment by yvesgoeleven** [comment]
@DPEWillems Het staat online, ik denk dat dit klaar is?

Ik vind het nog iets te vroeg om op facebook te gooien, de sint is echt nog 3 weken weg. Dus misschien dit issue sluiten en een nieuw maken voor facebook?

**Comment by yvesgoeleven** [comment]
@DPEWillems Ik plak gewoon de link in facebook en dan komt er automatisch een bericht op basis van de informatie in de frontmatter (title, description & cover)
