### ISSUE TITLE
Mountain bike: aankondiging opmaken (tekst)

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#55]
Woensdag 26 december
Sportcomplex De Vijfsprong Lummen

X-Masbikers MTB-tour

Vertrek tussen 08u00 en 11u00

•	Bewaakte fietsenstalling
•	Fietswash onderweg en bij aankomst
•	Depannagedienst voorzien
•	Bevoorrading voor alle afstanden en deelnemers
•	Boterhammen met spek bij aankomst 
•	Douches en kleedkamers aanwezig
•	Keuze tussen afstanden 25-35-45 kilometer
•	Uniek parcours door Lummen
•	Deelname 5 EUR - Korting voor leden van Fietspromo

![mtb](https://user-images.githubusercontent.com/471354/49338547-9db4e880-f622-11e8-9106-675cd14889bc.jpg)

**Comment by DPEWillems** [comment]
Is een link naar een externe website voldoende? Duiding nodig om het verband met/belang voor  BL aan te tonen?

**Comment by yvesgoeleven** [comment]
@DPEWillems Ik weet niet of er een externe website van is. Hier is alvast de tekt van vorig jaar https://github.com/BasketLummen/Website/blob/master/_content/news/_posts/2017-12-04-mountainbike.markdown

**Comment by DPEWillems** [comment]
PR #156 is geopend.

**Comment by DPEWillems** [comment]
achtergrond foro voor in de tekst zelf? Herfstbeeld uit Meldert...

is maar een suggestie:

![meldert700x700](https://user-images.githubusercontent.com/39502859/49340014-59354700-f63a-11e8-9f24-659019fb50a1.jpg)

**Comment by DPEWillems** [comment]
per vergissing gesloten

**Comment by yvesgoeleven** [comment]
@DPEWillems ik zou foto van patje met de jagermeister op beide plaatsen gebruiken...

**Comment by DPEWillems** [comment]
PR voor tekst gemerged
PR voor newsgrid gemerged
