### ISSUE TITLE
Kerstkamp U6-U10 Basket Lummen

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#56]
informatie tijdig doorsturen naar doelgroep, zodra de organisatie klaar is

**Comment by DPEWillems** [comment]
document op website updaten. Via Slack aan Brecht een update gevraagd.

**Comment by DPEWillems** [comment]
Luc M: zaal is gereserveerd (Dominique) op 2 en 3 januari 2019, 12-16h.

**Comment by DPEWillems** [comment]
Voor jongens en meisjes uit U8 en U10.  Er is nog geen beslissing of de U12 ook zullen kunnen meedoen.

E-mail naar Brecht gestuurd voor meer informatie.

**Comment by DPEWillems** [comment]
Marlies:
- voor U6, U8, U10
- enkel voor Basket Lummen
- 13h00-16h00
- 2 en 3 januari, spelers mogen 1 of twee dagen kiezen
- inschrijven is nodig - via website?
- inschijven tot ten laatste een week ervoor (2018-12-26).
- betalen ter plaatse (kassa)

**Comment by DPEWillems** [comment]
inschrijfformulier maken zoals bij 
http://www.basketlummen.be/news/2018-11-04-lummen-for-life/

**Comment by DPEWillems** [comment]
in Lummen	voor	elders	voor
21.12.2018	V				
22.12.2018	Z	Clinic	U8, U10 + U14-U18		
23.12.2018	Z				
24.12.2018	M				
25.12.2018	D				
26.12.2018	W	FROS	> 7 jaar, alleen BL		
27.12.2018	D	FROS	> 7 jaar, alleen BL		
28.12.2018	V	FROS	> 7 jaar, alleen BL		
29.12.2018	Z	kerststage	U12, alleen BL		
30.12.2018	Z				
31.12.2018	M				
01.01.2019	D				
02.01.2019	W	Kerstkamp	U6, U8, U10, alleen BL	Bounce Camp Hans Vanwijn	10-16 jaar
03.01.2019	D	Kerstkamp	U6, U8, U10, alleen BL	Bounce Camp Hans Vanwijn	10-16 jaar
04.01.2019	V			Bounce Camp Hans Vanwijn	10-16 jaar
05.01.2019	Z				
06.01.2019	Z

**Comment by DPEWillems** [comment]
Marlies:
Wij verwittigen de u6 dat ze een keer op woensdag trainen. De rest is sowieso aanwezig! 


Ik zou er geen uur bijzetten. De sint komt gewoon tijdens die training. Voor de rest prima! 😉

**Comment by yvesgoeleven** [comment]
Ik kan die inschrijvingen wel vezorgen

**Comment by DPEWillems** [comment]
Prijs gevraagd aan Marlies (voor invulformulier)

**Comment by yvesgoeleven** [comment]
@DPEWillems ondertussen beseft dat het niet nodig is want we hebben nu een module voor toernooien die ik ook kan gebruiken.

**Comment by yvesgoeleven** [comment]
Vorig jaar kostte het €5 per dag, maar je kon wel aparte dagen inschrijven, dat kan voorlopig niet met de toernooi module, kan zijn dat ik dat nog moet bijmaken

**Comment by DPEWillems** [comment]
Wat is het handigst? Het bestaande document aanpassen of een nieuw document en PR maken (maar dan met geüpdatete informatie) en dat publiceren (en het oude van de website halen)?

**Comment by yvesgoeleven** [comment]
Ik zou een nieuwe bericht aanmaken, want ook het inschrijvingsformulier moet er nog bij. Het vorige bericht is daar al op voorzien want we hebben er `Dit wordt later bekendgemaakt.` bijgezet. Eventueel kunnen we dat wel updaten door er een link naar het nieuwe bericht bij te zetten.

**Comment by yvesgoeleven** [comment]
Het heeft geen zin om fros & bouncecamp te herhalen, belangrijkste is het inschrijven voor U6 & U8
