### ISSUE TITLE
Kerststage voor de 3 U12 ploegen 2018-12-29

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#57]
Basketstage BL in december 2018: ook opnemen in overzicht (website + mailing)?

**Comment by DPEWillems** [comment]
tekst updaten? http://www.basketlummen.be/news/2018-10-19-kerstkampen/

**Comment by yvesgoeleven** [comment]
@DPEWillems is dit al definitief?

Indien wel zou ik er een aparte post voor maken

**Comment by DPEWillems** [comment]
Is inderdaad definitief, deze informatie is er:

Op  29/12/18 van 14u00 t.e.m. 18u00 organiseren we met Basket Lummen een Kerststage voor de 3 U12 ploegen.

Een korte tekst voor bij de nieuwsberichten (met een archieffoto?) lijkt me wel aangewezen - voor het werven en inschrijven maar ook als interessant nieuwsfeit over BL.

**Comment by yvesgoeleven** [comment]
@DPEWillems is er al nieuws voor de U8 & U10? Welke dagen gaan dat zijn?

**Comment by DPEWillems** [comment]
aanmeldingen U12C zijn ok, ook voor U12A en -B? Doelgroep alleen BLummen? Vraag aan Peter gesteld.
Op basis hiervan nieuwsitem opvatten als:
- promotie maken voor dit evenement (bij doelgroep) of
- vermelden als interessant nieuwsfeit voor de club, en achteraf eventueel een kort verslagje

**Comment by DPEWillems** [comment]
Peter:
- alleen voor Basket Lummen (U12)
- U12C ok, U12B ok, U12A vermoedelijk ook ok

Dus evenement vermelden als interessant feit? Of alleen achteraf een verslagje?

**Comment by yvesgoeleven** [comment]
Ik zou het houden bij een verslag, heeft geen nut apart aan te kondigen gezien het al via de FB/Whatsapp groepen is gecommuniceerd

**Comment by yvesgoeleven** [comment]
We kunnen het wel vermelden als we de aankondiging van U6/U8 doen, want daar zal wel een inschrijving voor zijn vermoed ik

**Comment by yvesgoeleven** [comment]
👍 om de originele kerstkampen tekst te updaten trouwens
