### ISSUE TITLE
Tie-Rock aankondiging maken

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#58]
aankondiging via website publiceren?
vanuit Facebook een link naar deze aankondiging op de website aanmaken?

**Comment by DPEWillems** [comment]
tekst van 2017:
https://github.com/BasketLummen/Website/blob/master/_content/news/_posts/2017-11-08-tie-rock.markdown

**Comment by DPEWillems** [comment]
wat feiten op een rij:

Tie-Rock
10e editie
Domino, Outback, Creep
zaterdag 24 november 2018, vanaf 19h30
VVK EUR 10,-
kassa EUR 12,-
verkrijgbaar bij:
- kantine sporthal Lummen
- Dozies Pub (Gemeenteplein, Lummen)
- Kom eens Kieken (Viversel, Zolder)
Grote verwarmde tent naast de kerk van Thiewinkel (Lummen).
ten voordele van Basket Lummen

**Comment by DPEWillems** [comment]
Is Johan Swinnen de juiste man met de juiste argumenten om promotie te maken?

**Comment by yvesgoeleven** [comment]
@DPEWillems Hij organiseert het
