### ISSUE TITLE
Tekst Supportersbus: Antwerp Giants DSE A 10/11

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#62]
Tijdstip: Vertrek om 19u
Locatie: sporthal
Prijs: €5
Maatschappij: Demerstee

**Comment by DPEWillems** [comment]
<
---
layout: post
title: "Supportersbus Antwerp Giants, 10 november"
date: 2018-11-06 12:00:00
description: De supportersbus naar de wedstrijd tegen de Antwerp Giants vertrekt om 19u aan de sporthal.
cover: /news/img/demerstee.jpg
permalink: /news/2018-11-06-supportersbus/
---

Supporter mee voor onze Dames A in hun wedstrijd tegen de Antwerp Giants!

We leggen een supportersbus in om allemaal samen naar deze wedstrijd kunnen gaan kijken, zonder zorgen en in een opperbeste sfeer.

Op zaterdag 10 november vertrekt de bus om 19u stipt aan Sporthal De Vijfsprong. Je komt best 10 minuutjes vroeger om het instappen rustig te laten verlopen. De rit (heen en terug, sporthal Roosendael in Merksem) kost amper €5 per persoon (betalen ter plaatse).

Wedstrijdgegevens vind je hier: [wedstrijdgegevens](http://www.basketlummen.be/match/?matchid=BVBL18199180NADSE11AKB)

Voor meer informatie kan je terecht bij onze sfeermaker van dienst: [Peter Corens](mailto://peter.corens@skynet.be)
>
