### ISSUE TITLE
Clinic

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#65]
Folder: https://www.facebook.com/qbasketball/photos/gm.204437933788978/2293276194237629/?type=3&theater

inschrijven via http://basketbal.vlaanderen/agenda/detail/coach-clinic-gerrit-driessens-lummen

vb clinic: https://www.youtube.com/watch?v=rwbNeHWRzrE&fbclid=IwAR0c9oxq8HZxtvAvzb2egwSJhZAW_JfypDI1GL2LCeZ4otASZrDlzxHEvts

**Comment by yvesgoeleven** [comment]
Clinic is niet voor spelers, maar voor coaches (ook van buiten de club), ik zou dat echt apart behandelen

**Comment by DPEWillems** [comment]
Prijs voor niet-BL-coaches nog te bepalen...

**Comment by yvesgoeleven** [comment]
@DPEWillems prijs staat vermeld op het inschrijvingsformulier; wij hoeven dat niet te vermelden in onze tekst naar mijn mening omdat we ons richten tot onze eigen coaches
