### ISSUE TITLE
Tekst Eindejaarsactie 2018

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#67]
Tekst gelijkaardig aan de tekst van vorig jaar, officieel formulier wordt nog bezorgd in digitaal formaat

https://github.com/BasketLummen/Website/blob/master/_content/news/_posts/2017-11-21-eindejaarsactie.markdown

**Comment by DPEWillems** [comment]
Is het de bedoeling het bestelformulier digitaal te maken (zoals een inschrijving) of digitaal aan te bieden om zelf af te printen, in te vullen en af te geven?

**Comment by DPEWillems** [comment]
ik zie het al: [bestel formulier](/news/downloads/eindejaarsactie_2017_formulier.pdf)

lijkt me prima om dit ook in 2018 zo te doen.

**Comment by DPEWillems** [comment]
dus nu nog even wachten op de e-mail van Annick met daarin:
- bestelformulier in .pdf
- uiterste besteldatum
- afhaalmoment
en dan kunnen we de tekst updaten en aanpassen (indien nodig).

**Comment by yvesgoeleven** [comment]
@DPEWillems ja net hetzelfde, het geld moet toch aan de coaches bezorgd worden, dus kunt dan formulier mee afgeven

**Comment by yvesgoeleven** [comment]
@DPEWillems dat is een goed voorstel

**Comment by DPEWillems** [comment]
PR aangemaakt.
