### ISSUE TITLE
Sponsormatch: Nieuwsbericht opstellen

### ISSUE THREAD

**Issue by DPEWillems** [BasketLummen/Communicatie#72]
Wat maakt de wedstrijd speciaal?
Is er een speciale activiteit voor, tijdens of na de wedstrijd?

**Comment by DPEWillems** [comment]
Blijft het bij een aankondiging, of zijn er speciale activiteiten tijdens deze wedstrijd?

**Comment by yvesgoeleven** [comment]
Done
