### ISSUE TITLE
Tekst op website Heren A - Hades A

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#75]
Zaterdag 8 December 20u30
Sportcomplex De Vijfsprong Lummen       

Onze Heren A ontvangen de ongeslagen leider uit de reeks van 1e provinciale Heren Limburg.
Mission Impossible of slagen onze mannen erin om te stunten?
Kom onze mannen aanmoedigen en steunen! 

matchlink: http://www.basketlummen.be/match/?matchid=BVBL18199120LIHSE11AAM

**Comment by DPEWillems** [comment]
mijn opmerking achtergelaten in Github/Website.
