### ISSUE TITLE
Dames B vs DBC Houthalen B & Dames A vs Amon Jeugd Gentson A

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#83]
Twee topwedstrijden voor onze seniors dames! Onze Dames B nemen het om 17u30 op tegen DBC Houthalen B. In Houthalen werd in de heenwedstrijd nipt verloren met twee punten en ongetwijfeld zal Lummen er alles aan willen doen om deze keer wel de punten in Lummen te houden. Om 20u30 nemen onze Dames A het op tegen Amon Jeugd Gentson A. Hier won Lummen in de heenwedstrijd met maar drie punten verschil. Gentson heeft de punten broodnodig en zal dus ongetwijfeld gemotiveerd aan de opsprong verschijnen; onze dames daarentegen willen hun 7e plaats in de rangschikking verstevigen. 

opm: indien mogelijk de twee ploegfoto's van de dames B en dames A naast elkaar?

**Comment by DPEWillems** [comment]
alvast een .markdown aangemaakt (voorstel voor tekst)


        Website/_content/news/_posts/2019-01-12-dames-topwedstrijden.markdown
      
branch: dames-topwedstrijden

**Comment by yvesgoeleven** [comment]
Tekst is goed, zal vanavond proberen een image te maken van de 2 teams. In het grote kader kan dat misschien wel, in een klein kadertje gaat het niet lukken denk ik.

**Comment by DPEWillems** [comment]
PR gemergd, zag ik. Nu nog een PR voor de nieuwsgrid ... Maak jij die aan,Yves?

**Comment by yvesgoeleven** [comment]
Is gebeurd en staat online
