### ISSUE TITLE
Heren B vs KBBC Miners Beringen C & Heren A vs BC Maasmechelen A

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#84]
Onze Heren B ontvangen om 18u30 de buren uit Beringen. KBBC Minders Beringen zal er op gebrand zijn om de nederlaag uit de heenwedstrijd uit te wissen, maar onze Heren B zijn aan een schitterend seizoen bezig en zullen ongetwijfeld de punten in Lummen willen houden. Voor onze Heren A is de wedstrijd tegen BC Maasmechelen de uitgelezen kans om uit de staart van de rangschikking te klimmen en hun derde thuiszege van de competitie te behalen.

**Comment by DPEWillems** [comment]
PR 169 aangemaakt
