### ISSUE TITLE
Aankondiging: She got game camp

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#87]
Flyer

![20190306_flyer_stagedag_shegotgame](https://user-images.githubusercontent.com/471354/51179949-4499cf00-18c7-11e9-9480-f71e1d3cf61d.jpg)

**Comment by DPEWillems** [comment]
Is dit voor iedereen of alleen leden van BT/Basket Lummen?

**Comment by DPEWillems** [comment]
Is het de bedoeling de stage te vermelden of er (extra) promotie voor te maken?

**Comment by yvesgoeleven** [comment]
@DPEWillems ja, en dat zou eigenlijk snel mogen. Het is open voor iedereen

**Comment by DPEWillems** [comment]
Zal er dit weekend naar kijken....

**Comment by DPEWillems** [comment]
Zijn er speciale kenmerken van deze stage, m.a.w. wat maakt deze stage bijzonder?

**Comment by DPEWillems** [comment]
De tekst die we al hadden lijkt me ook nog wel goed (met aanpassing van de praktische details):

https://www.basketlummen.be/news/2018-10-05-she-got-game/

**Comment by DPEWillems** [comment]
PR 175 aangemaakt - nog aanvullen met speciale kenmerken van de stage - indien nodig.

Eventueel de flyer als newsgridfoto gebruiken? Of beter in de markdown-test (omwille van het formaat)?

**Comment by yvesgoeleven** [comment]
Volgens mij is er niks speciaal te melden

**Comment by DPEWillems** [comment]
Dan lijkt me de tekst wel te voldoen.
