### ISSUE TITLE
Week van de vrijwilliger

### ISSUE THREAD

**Issue by yvesgoeleven** [BasketLummen/Communicatie#88]
https://www.dynamoproject.be/nieuws/week-van-de-vrijwilliger-2

**Comment by DPEWillems** [comment]
Wordt er door BL een bepaalde activiteit georganiseerd?

**Comment by yvesgoeleven** [comment]
ik heb helemaal geen idee eigenlijk, moet nog onderzocht worden. Maar belangrijkste is alle vrijwilligers bedanken
